# Generated by Django 3.2.16 on 2022-11-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('access_token', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
